name: Cucumber (with Godog)

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  test:
    name: Cucumber (with Godog)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            ref: ${{ github.head_ref }}

      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Install Godog
        run: go get github.com/cucumber/godog/cmd/godog@v0.11.0

      - name: Execute Cucumber BDD Specifications
        run: godog --format cucumber:test-results/cucumber-report.json

      - uses: actions/setup-node@v2
        with:
          node-version: '14'

       - name: Cache dependencies
           id: cache
           uses: actions/cache@v2
         with:
           path: ./node_modules
           key: modules-${{ hashFiles('package-lock.json') }}

  - name: Install dependencies
    if: steps.cache.outputs.cache-hit != 'true'
    run: npm ci --ignore-scripts
      - name: install cucumber-html-reporter
        run: npm install cucumber-html-reporter --save-dev

      - name: generate html report from cucumber-test-results
        run: node index.js

      # commit the changed test report
      - uses: stefanzweifel/git-auto-commit-action@v4

        with:
          # which file(s) to add
          file_pattern: test-results/cucumber-report.*

          commit_message: "new cucumber bdd test report, created by github action run"

          # Optional. Disable dirty check and always try to create a commit and push
          skip_dirty_check: true

          # Optional. Skip internal call to `git fetch`
          skip_fetch: true
