name: feature-linter

on: [push]

jobs:
  Gherkin-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: restqa/gherkin-linter-action@0.0.1
        with:
          path: 'features/'
          config_file: '.gherkin-lintrc'