name: run golang tests

on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  test:
    name: golang tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            ref: ${{ github.head_ref }}
      - name: Setup golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

     - name: Test
       run: go test ./...
