name: node

on:
  pull_request:


jobs:
  test:
    name: create test report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
            ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: install cucumber-html-reporter
        run: npm install cucumber-html-reporter --save-dev

      - name: generate html report from cucumber-test-results
        run: node index.js


